// per-project dev secrets, generated once into secrets.env (0600, git-ignored)
const crypto = require('node:crypto')
const fs = require('node:fs')
const paths = require('./paths.js')
const envfile = require('./envfile.js')

const FILE = 'secrets.env'

// no 0/O/1/l/I: these get read off a terminal and typed into a login form
const ALPHABET = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789'

// rejection sampling; a plain % would bias the low end
const password = (len = 20) => {
    const limit = 256 - (256 % ALPHABET.length)
    let out = ''
    while (out.length < len) {
        for (const b of crypto.randomBytes(len)) {
            if (b < limit) out += ALPHABET[b % ALPHABET.length]
            if (out.length === len) break
        }
    }
    return out
}

const hex = (bytes = 32) => crypto.randomBytes(bytes).toString('hex')

const GENERATORS = {
    LMA_JWT_SECRET: () => hex(),
    LMA_COOKIE_SECRET: () => hex(),
    LMA_ADMIN_PASSWORD: () => password(),
}

const WEAK = new Set([
    'medusa', 'medusa123', 'supersecret', 'password', 'password123', 'admin',
    'admin123', 'changeme', 'secret', '123456', '12345678', 'letmein', 'test',
])

const isWeak = (pw) => !pw || pw.length < 12 || WEAK.has(String(pw).toLowerCase())

const parse = envfile.parse

const format = (values) =>
    '# Generated by lma. Local dev only; not for any deployed environment.\n' +
    Object.entries(values).map(([k, v]) => `${k}='${String(v).replace(/'/g, `'\\''`)}'`).join('\n') + '\n'

const ensure = (root) => {
    const dir = paths.ensure(root)
    const file = require('node:path').join(dir, FILE)
    let values = {}
    try { values = parse(fs.readFileSync(file, 'utf8')) } catch { /* first run */ }
    let dirty = false
    for (const [key, gen] of Object.entries(GENERATORS)) {
        if (!values[key]) { values[key] = gen(); dirty = true }
    }
    if (dirty) {
        fs.writeFileSync(file, format(values), { mode: 0o600 })
        try { fs.chmodSync(file, 0o600) } catch { /* windows-ish filesystems */ }
    }
    return { file, values }
}

module.exports = { FILE, ensure, parse, format, password, hex, isWeak, WEAK }
